### ISSUE TITLE
Link to splink settings editor doesn't work

### ISSUE THREAD

**Issue by RossKen** [RobinL/robinl.github.io#111]
On [probabilistic record  linkage page](https://www.robinlinacre.com/probabilistic_linkage/) there is a reference to [splink settings editor](https://moj-analytical-services.github.io/splink_settings_editor/) which isn't rendering properly. Should this be pointing to https://moj-analytical-services.github.io/splink/settingseditor/editor.html instead?

**Comment by RobinL** [comment]
Thanks, fixed!
